# Generated by Django 4.2.27 on 2026-01-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_sort",
                    models.CharField(
                        default="protein_ratio_desc",
                        help_text="Default sort option",
                        max_length=100,
                    ),
                ),
                (
                    "items_per_page",
                    models.IntegerField(
                        default=20, help_text="Number of items per page"
                    ),
                ),
                (
                    "radius_options",
                    models.JSONField(
                        default=list,
                        help_text="Available radius options in miles (e.g., [5, 10, 25, 50])",
                    ),
                ),
                (
                    "default_map_center",
                    models.JSONField(
                        default=list,
                        help_text="Default map center [lng, lat] (e.g., [-74.0060, 40.7128])",
                    ),
                ),
                (
                    "default_map_zoom",
                    models.IntegerField(default=12, help_text="Default map zoom level"),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Config version for cache invalidation"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Configuration",
                "verbose_name_plural": "App Configuration",
            },
        ),
        migrations.CreateModel(
            name="FilterConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Filter name (e.g., 'calories', 'protein')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label for the filter", max_length=100
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measurement (e.g., 'g', 'kcal')",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(help_text="Array of filter options as JSON"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Filter Configuration",
                "verbose_name_plural": "Filter Configurations",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="QuickFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name/ID for the preset",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(help_text="Display label", max_length=100)),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon name (e.g., 'Zap', 'Heart')", max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of what this preset does"),
                ),
                (
                    "filter_params",
                    models.JSONField(help_text="Filter parameters as JSON object"),
                ),
                (
                    "requires_location",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this filter requires user location",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Quick Filter",
                "verbose_name_plural": "Quick Filters",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SortOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Internal sort value (e.g., 'protein_ratio_desc')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(help_text="Display label", max_length=100)),
                (
                    "requires_location",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this sort requires user location",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sort Option",
                "verbose_name_plural": "Sort Options",
                "ordering": ["order", "value"],
            },
        ),
    ]
