# Generated by Django 4.2.27 on 2026-01-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("website_url", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("nutrition_source_url", models.URLField(blank=True)),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("serving_size", models.CharField(blank=True, max_length=100)),
                ("calories", models.PositiveIntegerField()),
                ("protein", models.DecimalField(decimal_places=1, max_digits=5)),
                ("carbs", models.DecimalField(decimal_places=1, max_digits=5)),
                ("fat", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "fiber",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("sodium", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "sugar",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "saturated_fat",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_vegan", models.BooleanField(default=False)),
                ("is_gluten_free", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                ("source_url", models.URLField(blank=True)),
                ("last_verified", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="api.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-protein"],
            },
        ),
        migrations.CreateModel(
            name="DataFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("incorrect", "Incorrect Data"),
                            ("outdated", "Outdated Data"),
                            ("missing", "Missing Item"),
                        ],
                        max_length=50,
                    ),
                ),
                ("user_comment", models.TextField(blank=True)),
                ("user_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="api.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
