# Generated by Django 4.2.27 on 2026-01-28 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="location_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="RestaurantLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "osm_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="OpenStreetMap ID",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Location name (e.g., "Chipotle - Union Square")',
                        max_length=255,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("postcode", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="US", max_length=2)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verified by admin or user"
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="osm",
                        help_text="osm, user_submission, manual",
                        max_length=50,
                    ),
                ),
                (
                    "osm_amenity_type",
                    models.CharField(
                        blank=True, help_text="fast_food, restaurant", max_length=50
                    ),
                ),
                ("last_verified", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="api.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["restaurant__name", "city"],
            },
        ),
        migrations.CreateModel(
            name="LocationFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("closed", "Location Closed"),
                            ("wrong_address", "Wrong Address"),
                            ("duplicate", "Duplicate Entry"),
                            ("missing", "Location Missing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("user_comment", models.TextField(blank=True)),
                ("user_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="api.restaurantlocation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="restaurantlocation",
            index=models.Index(
                fields=["restaurant"], name="api_restaur_restaur_633a68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurantlocation",
            index=models.Index(
                fields=["latitude", "longitude"], name="api_restaur_latitud_6d2bf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurantlocation",
            index=models.Index(fields=["state"], name="api_restaur_state_9216fa_idx"),
        ),
    ]
