# Generated by Django 4.2.27 on 2026-01-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_restaurant_location_count_restaurantlocation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="brand_color",
            field=models.CharField(
                blank=True,
                default="#3B82F6",
                help_text="Hex color for map markers (e.g., #FF5733)",
                max_length=7,
            ),
        ),
    ]
