# Generated by Django 4.2.5 on 2026-02-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_restaurant_brand_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image_url",
            field=models.URLField(blank=True, help_text="URL to food photo thumbnail"),
        ),
    ]
