# Generated by Django 4.2.5 on 2026-02-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_add_menuitem_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Square icon for map markers and thumbnails",
                upload_to="restaurants/icons/",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="logo",
            field=models.ImageField(
                blank=True, help_text="Main logo image", upload_to="restaurants/logos/"
            ),
        ),
    ]
