# Generated by Django 4.2.5 on 2026-02-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_restaurant_icon_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='has_byo',
            field=models.BooleanField(default=False, help_text='Restaurant offers build-your-own bowls/meals'),
        ),
    ]
