# Generated by Django 4.2.5 on 2026-02-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_restaurant_has_byo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByoComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('base', 'Base'), ('protein', 'Protein'), ('topping', 'Topping'), ('dressing', 'Dressing/Sauce'), ('extra', 'Extra')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fiber', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('sodium', models.PositiveIntegerField(blank=True, null=True)),
                ('sugar', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('saturated_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byo_components', to='api.restaurant')),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
    ]
