# Generated by Django 4.2.5 on 2026-02-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_byo_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='nutrition_pdf',
            field=models.FileField(blank=True, help_text='Upload nutrition PDF to auto-parse menu items', upload_to='restaurants/pdfs/'),
        ),
    ]
