# Generated by Django 4.2.5 on 2026-02-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_restaurant_nutrition_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='has_drink_customizer',
            field=models.BooleanField(default=False, help_text='Restaurant has drink variants with size/milk options'),
        ),
    ]
