# Generated by Django 4.2.5 on 2026-02-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_drink_customizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='byo_noun',
            field=models.CharField(blank=True, default='', help_text='e.g. "Bowl", "Pizza", "Sub" — shown as "Build Your Own Pizza"', max_length=50),
        ),
    ]
